"""Pydantic data models for the MedAgent-Pro pipeline."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


# ── Disease / Task configuration ───────────────────────────────────


class TaskConfig(BaseModel):
    """Describes a diagnostic task (loaded from task.json)."""

    input: str = Field(..., description="Description of input modality, e.g. 'Fundus image'")
    disease: str = Field(..., description="Diagnostic goal, e.g. 'Diagnose potential glaucoma'")


class ToolDefinition(BaseModel):
    """A single tool available in the toolset (loaded from toolset.json)."""

    id: int
    type: str
    function: str
    input: str = ""
    output: str = ""
    command: str = ""


# ── Plan ───────────────────────────────────────────────────────────


class PlanStep(BaseModel):
    """One step in a diagnostic plan (generated by the Planner agent)."""

    id: int
    tool: list[int] = Field(default_factory=list)
    action_type: str = Field(..., description="'qualitative' or 'quantitative'")
    action: str = ""
    input_type: list[int] = Field(default_factory=list, description="0 = raw input, else prior step id")
    output_type: str = Field(..., description="'intermediate result' or 'final indicator'")
    output_path: str = "diagnosis.json"


# ── Diagnosis ──────────────────────────────────────────────────────


class DiagnosticIndicator(BaseModel):
    """An indicator extracted during case-level analysis."""

    indicator_name: str
    if_abnormal: dict[str, Any] = Field(default_factory=dict)
    value: float | None = None


class WeightedIndicator(BaseModel):
    """Indicator with its clinical weight (output of the Decider)."""

    indicator_name: str
    weight: float


class DiagnosisResult(BaseModel):
    """Final structured diagnosis produced by the Decider agent."""

    diagnosis: str
    confidence: float = 0.0
    threshold: float = 0.5
    weighted_score: float = 0.0
    weights: list[WeightedIndicator] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    notes: str = ""


# ── LangGraph state ───────────────────────────────────────────────


class WorkflowState(BaseModel):
    """Shared state passed between LangGraph nodes."""

    # inputs
    disease_dir: str = ""
    image_path: str = ""

    # task-level
    task_config: TaskConfig | None = None
    toolset: list[ToolDefinition] = Field(default_factory=list)
    rag_context: str = ""
    plan: list[PlanStep] = Field(default_factory=list)

    # case-level
    current_step_index: int = 0
    save_dir: str = ""
    step_results: dict[str, Any] = Field(default_factory=dict)
    brief_diagnosis: dict[str, Any] = Field(default_factory=dict)
    indicators: list[DiagnosticIndicator] = Field(default_factory=list)

    # output
    diagnosis: DiagnosisResult | None = None
    error: str = ""
